sudo: false
language: rust

matrix:
  include:
  - env: TARGET=x86_64-unknown-linux-gnu

script:
  - bash ci/script.sh

after_script: set +e

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master
