[package]
name = "t-rust-less"
version = "0.1.0"
authors = ["Untoldwind <landru@untoldwind.net>"]
build = "build.rs"
edition = "2018"

[dependencies]
serde = "1"
serde_derive = "1"
serde_json = "1"
data-encoding = "2"
openssl = { version = "0", features = ["vendored"] }
byteorder = "1.2.4"
chrono = { version = "0", features = ["serde"] }
url = "1"
circular = "0"
num-derive = "0"
num-traits = "0"
ring = "0"
secrets = "0"
argon2rs = "0"
clap = { version = "2", default-features = false, features = ["suggestions", "color"]}
capnp = "0"

[dev-dependencies]
tempdir = "0"
spectral = "0"
rand = "0"

[target.x86_64-unknown-linux-gnu.dependencies]
x11 = "2"

[build-dependencies]
clap = { version = "2", default-features = false, features = ["suggestions", "color"]}
capnpc = "0"