[package]
name = "t-rust-less"
version = "0.1.0"
authors = ["Untoldwind <landru@untoldwind.net>"]
build = "build.rs"

[dependencies]
error-chain = "0.12.0"
serde_json = "1.0.24"
data-encoding = "2.1.1"
openssl = { version = "0.10.11", features = ["vendored"] }
byteorder = "1.2.4"

[dependencies.clap]
version = "2.32.0"
default-features = false
features = ["suggestions", "color"]

[build-dependencies.clap]
version = "2.32.0"
default-features = false
features = ["suggestions", "color"]


[patch.crates-io]
openssl = { git = "https://github.com/untoldwind/rust-openssl.git" }
