[workspace]
members = [
    "lib",
    "cli"
]

[patch.crates-io]
x25519-dalek = { git = "https://github.com/untoldwind/x25519-dalek.git"}
openssl = { git = "https://github.com/untoldwind/rust-openssl.git" }