[package]
name = "t-rust-less-cli"
version = "0.1.0"
authors = ["Untoldwind <landru@untoldwind.net>"]
build = "build.rs"
edition = "2018"

[dependencies]
log = "0"
env_logger = "0"
clap = { version = "2", default-features = false, features = ["suggestions", "color"]}
atty = "0.2"
t-rust-less-lib = { path = "../lib" }
zxcvbn = "1"
serde = "1"
serde_derive = "1"
rand = "0.5"
dirs = "1"
toml = "0"
url = "1"

[target.'cfg(unix)'.dependencies]
cursive = { version = "0", default-features = false, features = ["termion-backend"]}
termion="1"

[target.'cfg(windows)'.dependencies]
cursive = { version = "0", default-features = false, features = ["pancurses-backend"]}

[dev-dependencies]
tempdir = "0"
spectral = "0"

[build-dependencies]
clap = { version = "2", default-features = false, features = ["suggestions", "color"]}
