[package]
name = "t-rust-less-cli"
version = "0.1.0"
authors = ["Untoldwind <landru@untoldwind.net>"]
build = "build.rs"
edition = "2018"

[dependencies]
clap = { version = "2", default-features = false, features = ["suggestions", "color"]}
t-rust-less-lib = { path = "../lib" }
zxcvbn = "1"

[dev-dependencies]
tempdir = "0"
spectral = "0"

[target.'cfg(unix)'.dependencies]
xcb = { version = "0.8", features = [ "thread", "xfixes" ] }
libc = "0"

[target.'cfg(windows)'.dependencies]
winapi = "0"

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
mach_o_sys = "0"

[build-dependencies]
clap = { version = "2", default-features = false, features = ["suggestions", "color"]}
capnpc = "0"

