[package]
name = "t-rust-less-daemon"
version = "0.1.0"
authors = ["Untoldwind <landru@untoldwind.net>"]
build = "build.rs"
edition = "2018"

[dependencies]
log = "0"
env_logger = "0"
clap = { version = "2", default-features = false, features = ["suggestions", "color"]}
t-rust-less-lib = { path = "../lib" }
capnp = "0.12"
capnp-rpc = "0.12"
futures = "0.3"
tokio = { version = "0.2", features = ["net", "rt-util", "signal", "stream", "time"] }
tokio-util = { version = "0.3", features = ["compat"] }

[target.'cfg(unix)'.dependencies]
libc = "0"

[build-dependencies]
clap = { version = "2", default-features = false, features = ["suggestions", "color"]}
